package openssh

// Keywords is every sshd_config keyword, in sshd's own spelling.
//
// It exists because the two sources this tool reads disagree about case.
// `sshd -T` lower-cases everything it prints, and a configuration file may be
// written in any case at all — sshd matches keywords case-insensitively — so
// without a canonical list the settings table would show `permitrootlogin`
// from one machine and `PermitRootLogin` from the next, and the two would not
// join up.
//
// The list is from sshd_config(5) as of OpenSSH 9.9. It does not need to be
// exhaustive to be useful: a keyword that is missing is shown exactly as the
// server spelled it, which is the same behaviour a brand new keyword gets.
var Keywords = []string{
	"AcceptEnv",
	"AddressFamily",
	"AllowAgentForwarding",
	"AllowGroups",
	"AllowStreamLocalForwarding",
	"AllowTcpForwarding",
	"AllowUsers",
	"AuthenticationMethods",
	"AuthorizedKeysCommand",
	"AuthorizedKeysCommandUser",
	"AuthorizedKeysFile",
	"AuthorizedPrincipalsCommand",
	"AuthorizedPrincipalsCommandUser",
	"AuthorizedPrincipalsFile",
	"Banner",
	"CASignatureAlgorithms",
	"ChallengeResponseAuthentication",
	"ChannelTimeout",
	"ChrootDirectory",
	"Ciphers",
	"ClientAliveCountMax",
	"ClientAliveInterval",
	"Compression",
	"DenyGroups",
	"DenyUsers",
	"DisableForwarding",
	"ExposeAuthInfo",
	"FingerprintHash",
	"ForceCommand",
	"GatewayPorts",
	"GSSAPIAuthentication",
	"GSSAPICleanupCredentials",
	"GSSAPIStrictAcceptorCheck",
	"HostbasedAcceptedAlgorithms",
	"HostbasedAuthentication",
	"HostbasedUsesNameFromPacketOnly",
	"HostCertificate",
	"HostKey",
	"HostKeyAgent",
	"HostKeyAlgorithms",
	"IgnoreRhosts",
	"IgnoreUserKnownHosts",
	"Include",
	"IPQoS",
	"KbdInteractiveAuthentication",
	"KerberosAuthentication",
	"KerberosGetAFSToken",
	"KerberosOrLocalPasswd",
	"KerberosTicketCleanup",
	"KexAlgorithms",
	"ListenAddress",
	"LoginGraceTime",
	"LogLevel",
	"LogVerbose",
	"MACs",
	"Match",
	"MaxAuthTries",
	"MaxSessions",
	"MaxStartups",
	"ModuliFile",
	"PasswordAuthentication",
	"PermitEmptyPasswords",
	"PermitListen",
	"PermitOpen",
	"PermitRootLogin",
	"PermitTTY",
	"PermitTunnel",
	"PermitUserEnvironment",
	"PermitUserRC",
	"PerSourceMaxStartups",
	"PerSourceNetBlockSize",
	"PerSourcePenalties",
	"PerSourcePenaltyExemptList",
	"PidFile",
	"Port",
	"PrintLastLog",
	"PrintMotd",
	"PubkeyAcceptedAlgorithms",
	"PubkeyAuthOptions",
	"PubkeyAuthentication",
	"RDomain",
	"RefuseConnection",
	"RekeyLimit",
	"RequiredRSASize",
	"RevokedKeys",
	"SecurityKeyProvider",
	"SetEnv",
	"StreamLocalBindMask",
	"StreamLocalBindUnlink",
	"StrictModes",
	"Subsystem",
	"SyslogFacility",
	"TCPKeepAlive",
	"TrustedUserCAKeys",
	"UnusedConnectionTimeout",
	"UseDNS",
	"UsePAM",
	"VersionAddendum",
	"X11DisplayOffset",
	"X11Forwarding",
	"X11UseLocalhost",
	"XAuthLocation",
}
